export const FONT_FAMILIES = [
  "Alfa Slab One",
  "Amatic SC",
  "Arial",
  "Arimo",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Calistoga",
  "Caveat",
  "Comfortaa",
  "Comic Sans MS",
  "Courier New",
  "Dela Gothic One",
  "EB Garamond",
  "Georgia",
  "Hachi Maru Pop",
  "Hina Mincho",
  "IBM Plex Sans JP",
  "Impact",
  "Kaisei Decol",
  "Kaisei HarunoUmi",
  "Kaisei Opti",
  "Kaisei Tokumin",
  "Klee One",
  "Kosugi",
  "Kosugi Maru",
  "Lexend",
  "Lobster",
  "Lora",
  "M PLUS 1",
  "M PLUS 1 Code",
  "M PLUS 1p",
  "M PLUS 2",
  "M PLUS Rounded 1c",
  "Merriweather",
  "Mochiy Pop One",
  "Mochiy Pop P One",
  "Montserrat",
  "Murecho",
  "New Tegomin",
  "Noto Sans JP",
  "Nunito",
  "Oswald",
  "Pacifico",
  "Playfair Display",
  "Potta One",
  "Proxima Nova",
  "Rampart One",
  "Reggae One",
  "Roboto",
  "Roboto Mono",
  "Roboto Serif",
  "RocknRoll One",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Shippori Antique",
  "Shippori Antique B1",
  "Spectral",
  "Stick",
  "Times",
  "Times New Roman",
  "Train One",
  "Trebuchet MS",
  "Verdana",
  "Yomogi",
  "Yuji Boku",
  "Yuji Mai",
  "Yuji Syuku",
  "Yusei Magic",
  "Zen Antique",
  "Zen Antique Soft",
  "Zen Kaku Gothic Antique",
  "Zen Kaku Gothic New",
  "Zen Kurenaido",
  "Zen Maru Gothic",
  "Zen Old Mincho",
] as const;

export type FontFamily = (typeof FONT_FAMILIES)[number];
